<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Utilidades" Id="{63cd07ee-28a3-4f22-aefc-aaddc9ee9d5c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Utilidades
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Direccionamiento de variables para enviar 
Var_Com_CH4_MulDis.aStringCom[62] := Fecha_PLC.StringDateHourMin;]]></ST>
    </Implementation>
    <LineIds Name="Utilidades">
      <LineId Id="18" Count="0" />
      <LineId Id="21" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>