<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FinProduccionTemporizado" Id="{9763ee12-8e50-438b-98e7-87fbb4066f00}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FinProduccionTemporizado
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR	
	RutaHorno:(Ninguna, Linea5, Linea4_Inf,Linea4_Sup, Linea3, Linea2);
	Estado_FPT:(SalGreenCut_Temp, EntSecadero_Temp, SalAirless_Temp, EntSup_Temp, EntInf_Temp);
	intRutaHorno:INT;
END_VAR
VAR RETAIN
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Al activar el fin de producción temporizado empezará un ciclo con temporizadores el cual irá desde la prensa a la entrada del horno reseteando los contadores de piezas.
RutaHorno:=intRutaHorno;
]]></ST>
    </Implementation>
    <LineIds Name="FinProduccionTemporizado">
      <LineId Id="9" Count="0" />
      <LineId Id="29" Count="0" />
      <LineId Id="43" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>