<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Utilidades_1" Id="{6888e73a-9c15-48f8-a680-93406fd4e4af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Utilidades_1
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_Funciones_Paro.Temporizador1min(IN:=not GVL_Funciones_Paro.Temporizador1min.Q , PT:= T#60s, Q=> , ET=> );]]></ST>
    </Implementation>
    <LineIds Name="Utilidades_1">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>